stages:
  - install
  - lint          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

install-job:
  stage: install
  script:
    - npm install

lint-format-job:
  stage: lint
  script:
    - npm run lint:fix
    - npm run format

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - npm test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm run build

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
