default:
  image: node:16.19.0

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - lint          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

lint-format-job:
  stage: lint
  script:
    - echo $CI_COMMIT_REF_SLUG
    - npm run lint

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - npm test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm run build

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
